server:
  port: 8080
  servlet:
    contextPath: /api
zuul:
  routes:
    list:
      path: /api/list/**
      url: http://${GL_LIST_SERVICE_SERVICE_HOST}:${GL_LIST_SERVICE_SERVICE_PORT}
      stripPrefix: false
    dept:
      path: /api/dept/**
      url: http://${GL_DEPT_SERVICE_SERVICE_HOST}:${GL_DEPT_SERVICE_PORT}
      stripPrefix: false