server:
  port: 8080
  servlet:
    contextPath: /api
zuul:
  routes:
    list:
      path: /list/**
      url: http://gl-list-service:8080
      stripPrefix: false
      
    dept:
      path: /dept/**
      url: http://gl-dept-service:8080
      stripPrefix: false
    item:
      path: /item/**
      url: http://gl-item-service:8080
      stripPrefix: false