apiVersion: v1
kind: Service
metadata:
  name: gl-api-service
  labels:
    app: gl-api
  spec:
    type: ClusterIp
    sessionAffinity: ClientIP
    ports:
    - port: 8080
      protocol: TCP
    selector:
      app: gl-api